### ISSUE TITLE
Error "Sorry Something went wrong while executing Electrum"

### ISSUE THREAD

**Issue by walesc** [fujicoin/electrum-fjc#5]
Hi everyone,
I got this error after configuring Electrum and launching for the first time, any idea what might have caused this ?

Traceback (most recent call last):
  File "electrum\util.py", line 851, in run_with_except_hook
  File "threading.py", line 864, in run
  File "C:\Users\Wal\AppData\Local\Temp\_MEI105962\electrum\plugins\trustedcoin\trustedcoin.py", line 474, in f
    return func(self, *args, **kwargs)
  File "C:\Users\Wal\AppData\Local\Temp\_MEI105962\electrum\plugins\trustedcoin\trustedcoin.py", line 495, in request_billing_info
    raise Exception(f'unexpected trustedcoin billing address: '
Exception: unexpected trustedcoin billing address: calculated fc1q2rd98lqjkz9wszwshsgjt9dpca35eqwzu4yh5e, received bc1q2rd98lqjkz9wszwshsgjt9dpca35eqwzx3kd5c
 
Additional information
Electrum version: 3.3.9 
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] 
Operating system: Windows-10-10.0.19041 
Wallet type: 2fa 
Locale: fr_FR 

Thanks in advance

**Comment by fujicoin** [comment]
You won't be able to use 2FA until Trustedcoin supports Fujicoin.

**Comment by walesc** [comment]
Thanks for the answer, what config am I supposed to use in electrum then ?

**Comment by fujicoin** [comment]
Select Standard wallet. Then try with the default settings.

**Comment by walesc** [comment]
Thanks
